application: yumedailyreport
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /images
  static_dir: images

- url: /style.css
  static_files: style.css
  upload: style.css

- url: /
  script: main.app
  login: admin

- url: /reports
  script: main.app
  login: admin

- url: /previewreport
  script: main.app
  login: admin

- url: /createreport
  script: main.app
  login: admin

- url: /report/.*
  script: main.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
